### ISSUE TITLE
Question regarding a project I'm working on

### ISSUE THREAD

**Issue by volitank** [MaxTaggart/columnar#13]
Hello @MaxTaggart, 

I am working on a project that uses columnar. Right now I have columnar.py packaged with the project because there is a small change I have made. I just removed this line below because I didn't want the formatting to be Uppercase.

`headers = [text.upper() for text in headers]`

I am not sure if this is something you would like to make configurable or not. 

The main reason I am contacting you through here is that in my project I am going to start a contributors log and wanted to see if you would like to be included. Columnar does a lot of our formatting so I think you have contributed a lot. If you would like to be included please send me the information you would like to be in the file. It will be visible in the source code.

You can reply to this or email me at blake@volian.org.

If you're interested in the project the source code is below. It is a wrapper for the apt package manager to make the output prettier. There is a big update incoming for v0.1.1. Thank you and have a wonderful rest of your day.

https://salsa.debian.org/volian-team/nala

**Comment by acksmaggart** [comment]
Hey @volitank , thanks for reaching out. Yes, in hindsight that was probably not the right default. I just pushed out an updated version, 1.4.0, which includes a new flag called `preformatted_headers` which, when set to `True`, will use the headers as provided without capitalizing them. Let me know if that isn't what you had in mind though.

About the contributor log, thanks for the offer! Please feel free to add my name (Max Taggart) and a link to my GitHub profile ( https://github.com/MaxTaggart )

**Comment by acksmaggart** [comment]
I'm going to close this for the sake of house-keeping but happy to re-open it if you think it should be open still.
