### ISSUE TITLE
Color regex question

### ISSUE THREAD

**Issue by RaitaroH** [MaxTaggart/columnar#8]
I wrote a script using this library. Thank you for it! 
My problem is that I would like to output colored text for anything ending with "mp4" at the end. This can vary A LOT, but it ends with ".mp4". According to [python regex](https://www.w3schools.com/python/python_regex.asp) doing something like "mp4\Z" or "mp4$" should work. It doesn't with the example provided in the readme. I also tried ".mp4+" and other combinations. Did I miss something? 

```py
#!/bin/python3

from columnar import columnar
from click import style

data = [
    ['Strade Bianche.mp4', 'Saturday 9th March', 'Tuscany, Italy', "Men's - 176km / Women's - 103km. Both men's and women's "],
    ['Omloop Het Nieuwsblad', 'Saturday 2nd March', 'Gent, Belgium', "Men's - 200km / Women's - 130km"],
    ['Milan-San Remo', 'Saturday 23rd March', 'Milan to San Remo, Italy', '295km'],
    ['Tour of Flanders', 'Sunday 7th April', 'Antwerp to Oudenaarde, Flanders region, Belgium', '260km']
]

patterns = [
    ('Saturday.+', lambda text: style(text, fg='white', bg='blue')),
    ('\d+km', lambda text: style(text, fg='cyan')),
    ('Omloop Het Nieuwsblad', lambda text: style(text, fg='green')),
    ('mp4$', lambda text: style(text, fg='green')),
    ('Milan-San Remo', lambda text: style(text, fg='red')),
    ('Tour of Flanders', lambda text: style(text, fg='yellow')),
]

table = columnar(data, headers=['Race', 'Date', 'Location', 'Distance'], patterns=patterns)
print(table)
```
![image](https://user-images.githubusercontent.com/19552720/78970859-f9468e80-7b12-11ea-97c5-2d0edb4eb871.png)

**Comment by acksmaggart** [comment]
Hey @RaitaroH , glad you like the library. Sorry for the delayed response. Can you provide an example script that will reproduce the bug you are seeing?

**Comment by acksmaggart** [comment]
Aha, I see now that you added a line to the `patterns` list with `'mp4$'`. However, I don't see anything in the `data` arrays that contains `"mp4"`. Am I misunderstanding your question?

**Comment by RaitaroH** [comment]
Hello,
I have already provided a code. Is right in the first comment.
```
data = [
    ['Strade Bianche.mp4', 'Saturday 9th March', 'Tuscany, Italy', "Men's - 176km / Women's - 103km. Both men's and women's "],
```

as you can see.

What I want to get out of this is this: I am using this project for a download interface. Sometimes in the name column I have things that end with mp4, or mkv, or have 1080p in the name etc.  As you can tell is for torrents. My problem is I cannot quite understand how the regexp is supposed to work?


In that link I provided it was stated that:
```
\Z | Returns a match if the specified characters are at the end of the string
```
So that's why I tried `mp4\Z`, `mp4$` etc. 
```
('mp4$', lambda text: style(text, fg='green')),
```
![image](https://user-images.githubusercontent.com/19552720/80273759-b9b89e80-86dd-11ea-9169-6b6f92f21b19.png)
So I would like that `Strade Bianche.mp4` to be green because it ends with mp4. I don't want to have a `Strade Bianche.mp4` rule because I don't know the first part, all I know is it ends with mp4, or mkv, or has 1080p in the name somewhere etc.

What parameters can I use so that I get anything with mkv in the name to be colored idk red, anything with mp4 in the name should be green etc.  Ideally I would like something obvious and that I can modify in order to add extra colors.

**Comment by acksmaggart** [comment]
@RaitaroH , sorry for all the confusion. I am finally getting back to this and I think I figured out the issue. There was an error in the Readme which said that the patterns were applied using `re.search`, but they are actually applied using `re.match`, so the regex has to match the whole content of the cell. So changing your regex to `.*mp4\Z` or `.*mp4$` will work. So, this snippet should work:

``` python
from columnar import columnar
from click import style

data = [
    ['Strade Bianche.mp4', 'Saturday 9th March', 'Tuscany, Italy', "Men's - 176km / Women's - 103km. Both men's and women's "],
    ['Omloop Het Nieuwsblad', 'Saturday 2nd March', 'Gent, Belgium', "Men's - 200km / Women's - 130km"],
    ['Milan-San Remo', 'Saturday 23rd March', 'Milan to San Remo, Italy', '295km'],
    ['Tour of Flanders', 'Sunday 7th April', 'Antwerp to Oudenaarde, Flanders region, Belgium', '260km']
]

patterns = [
    ('Saturday.+', lambda text: style(text, fg='white', bg='blue')),
    ('\d+km', lambda text: style(text, fg='cyan')),
    ('Omloop Het Nieuwsblad', lambda text: style(text, fg='green')),
    ('.*mp4$', lambda text: style(text, fg='green')),
    ('Milan-San Remo', lambda text: style(text, fg='red')),
    ('Tour of Flanders', lambda text: style(text, fg='yellow')),
]

table = columnar(data, headers=['Race', 'Date', 'Location', 'Distance'], patterns=patterns)
print(table)
```

Sorry about that. I have updated the Readme. Let me know if that doesn't resolve the issue and Ill re-open.
